/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package JobApplicationRecordService.model.impl;

import JobApplicationRecordService.model.Job_Application_Records;

import JobApplicationRecordService.service.Job_Application_RecordsLocalServiceUtil;

import aQute.bnd.annotation.ProviderType;

/**
 * The extended model base implementation for the Job_Application_Records service. Represents a row in the &quot;KMB_Job_Application_Records&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Job_Application_RecordsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Job_Application_RecordsImpl
 * @see Job_Application_Records
 * @generated
 */
@ProviderType
public abstract class Job_Application_RecordsBaseImpl
	extends Job_Application_RecordsModelImpl implements Job_Application_Records {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a job_ application_ records model instance should use the {@link Job_Application_Records} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Job_Application_RecordsLocalServiceUtil.addJob_Application_Records(this);
		}
		else {
			Job_Application_RecordsLocalServiceUtil.updateJob_Application_Records(this);
		}
	}
}