/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package JobApplicationRecordService.service.base;

import JobApplicationRecordService.model.Job_Application_Records;

import JobApplicationRecordService.service.Job_Application_RecordsService;

import JobApplicationRecordService.service.persistence.Job_Application_RecordsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the job_ application_ records remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link JobApplicationRecordService.service.impl.Job_Application_RecordsServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobApplicationRecordService.service.impl.Job_Application_RecordsServiceImpl
 * @see JobApplicationRecordService.service.Job_Application_RecordsServiceUtil
 * @generated
 */
public abstract class Job_Application_RecordsServiceBaseImpl
	extends BaseServiceImpl implements Job_Application_RecordsService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link JobApplicationRecordService.service.Job_Application_RecordsServiceUtil} to access the job_ application_ records remote service.
	 */

	/**
	 * Returns the job_ application_ records local service.
	 *
	 * @return the job_ application_ records local service
	 */
	public JobApplicationRecordService.service.Job_Application_RecordsLocalService getJob_Application_RecordsLocalService() {
		return job_Application_RecordsLocalService;
	}

	/**
	 * Sets the job_ application_ records local service.
	 *
	 * @param job_Application_RecordsLocalService the job_ application_ records local service
	 */
	public void setJob_Application_RecordsLocalService(
		JobApplicationRecordService.service.Job_Application_RecordsLocalService job_Application_RecordsLocalService) {
		this.job_Application_RecordsLocalService = job_Application_RecordsLocalService;
	}

	/**
	 * Returns the job_ application_ records remote service.
	 *
	 * @return the job_ application_ records remote service
	 */
	public Job_Application_RecordsService getJob_Application_RecordsService() {
		return job_Application_RecordsService;
	}

	/**
	 * Sets the job_ application_ records remote service.
	 *
	 * @param job_Application_RecordsService the job_ application_ records remote service
	 */
	public void setJob_Application_RecordsService(
		Job_Application_RecordsService job_Application_RecordsService) {
		this.job_Application_RecordsService = job_Application_RecordsService;
	}

	/**
	 * Returns the job_ application_ records persistence.
	 *
	 * @return the job_ application_ records persistence
	 */
	public Job_Application_RecordsPersistence getJob_Application_RecordsPersistence() {
		return job_Application_RecordsPersistence;
	}

	/**
	 * Sets the job_ application_ records persistence.
	 *
	 * @param job_Application_RecordsPersistence the job_ application_ records persistence
	 */
	public void setJob_Application_RecordsPersistence(
		Job_Application_RecordsPersistence job_Application_RecordsPersistence) {
		this.job_Application_RecordsPersistence = job_Application_RecordsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return Job_Application_RecordsService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Job_Application_Records.class;
	}

	protected String getModelClassName() {
		return Job_Application_Records.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = job_Application_RecordsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = JobApplicationRecordService.service.Job_Application_RecordsLocalService.class)
	protected JobApplicationRecordService.service.Job_Application_RecordsLocalService job_Application_RecordsLocalService;
	@BeanReference(type = Job_Application_RecordsService.class)
	protected Job_Application_RecordsService job_Application_RecordsService;
	@BeanReference(type = Job_Application_RecordsPersistence.class)
	protected Job_Application_RecordsPersistence job_Application_RecordsPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}