/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package Aggregation.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the customFieldAggregationTable service. Represents a row in the &quot;kmb_customFieldAggregationTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link Aggregation.model.impl.customFieldAggregationTableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Aggregation.model.impl.customFieldAggregationTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see customFieldAggregationTable
 * @see Aggregation.model.impl.customFieldAggregationTableImpl
 * @see Aggregation.model.impl.customFieldAggregationTableModelImpl
 * @generated
 */
@ProviderType
public interface customFieldAggregationTableModel extends BaseModel<customFieldAggregationTable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom field aggregation table model instance should use the {@link customFieldAggregationTable} interface instead.
	 */

	/**
	 * Returns the primary key of this custom field aggregation table.
	 *
	 * @return the primary key of this custom field aggregation table
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this custom field aggregation table.
	 *
	 * @param primaryKey the primary key of this custom field aggregation table
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the user ID of this custom field aggregation table.
	 *
	 * @return the user ID of this custom field aggregation table
	 */
	public int getUserId();

	/**
	 * Sets the user ID of this custom field aggregation table.
	 *
	 * @param UserId the user ID of this custom field aggregation table
	 */
	public void setUserId(int UserId);

	/**
	 * Returns the sap ID of this custom field aggregation table.
	 *
	 * @return the sap ID of this custom field aggregation table
	 */
	public int getSapId();

	/**
	 * Sets the sap ID of this custom field aggregation table.
	 *
	 * @param SapId the sap ID of this custom field aggregation table
	 */
	public void setSapId(int SapId);

	/**
	 * Returns the cgpa of this custom field aggregation table.
	 *
	 * @return the cgpa of this custom field aggregation table
	 */
	public double getCgpa();

	/**
	 * Sets the cgpa of this custom field aggregation table.
	 *
	 * @param Cgpa the cgpa of this custom field aggregation table
	 */
	public void setCgpa(double Cgpa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		Aggregation.model.customFieldAggregationTable customFieldAggregationTable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Aggregation.model.customFieldAggregationTable> toCacheModel();

	@Override
	public Aggregation.model.customFieldAggregationTable toEscapedModel();

	@Override
	public Aggregation.model.customFieldAggregationTable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}